### ISSUE TITLE
cannot launch docusaurus docs

### ISSUE THREAD

**Issue by radekjakubowski** [LunaticMuch/docusaurus-terminology#9]
cannot run existing docs. Crashes with exception 

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:429:7)
    at Object.module.exports [as plugin] (D:\pct4\pct-docs\pct4-docs\node_modules\@lunaticmuch\docusaurus-terminology\src\index.js:27:27)
    at initializePlugin (D:\pct4\pct-docs\pct4-docs\node_modules\@docusaurus\core\lib\server\plugins\init.js:83:61)
    at async Promise.all (index 6)
    at async initPlugins (D:\pct4\pct-docs\pct4-docs\node_modules\@docusaurus\core\lib\server\plugins\init.js:91:21)
    at async externalCommand (D:\pct4\pct-docs\pct4-docs\node_modules\@docusaurus\core\lib\commands\external.js:17:21)
    at async file:///D:/pct4/pct-docs/pct4-docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:231:3 {
  code: 'ERR_INVALID_ARG_TYPE'
  
  termsURL is undefined here, dunno why because in default options it is given but it's not relative.
  I've managed to override those with a tuple config `['@lunaticmuch/docusaurus-terminology', { termsUrl: './docs/terminology', termsDir: './docs/terminology'}]` but now it says that 
![image](https://user-images.githubusercontent.com/83402116/218751599-19c47a2d-b652-4517-9c50-92a6f98c8449.png)
despite pointing to real folder with .md files in it.

**Comment by radekjakubowski** [comment]
gr8 job from Pytak. It works now but there's another issue. URL which is generated for replaced item points into wrong place, e.g. http://localhost:3000/docs/developer-guides//docs/terminology/applicationTemplate

**Comment by LunaticMuch** [comment]
Oh I missed this. Is it still current?

**Comment by LunaticMuch** [comment]
This is now being fixed in version 2 out later today
